package dev.vsdeadshot.flashcards.data.local;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
import java.time.Instant;

/**
 * A generated card nobody has accepted yet.
 *
 * <p>Its own table rather than a flag on {@code card}, because a candidate must never appear in
 * the study queue, in the outbox, or in the set a pull is allowed to delete — and a flag would
 * leave it one forgotten {@code where} clause away from all three. The same reasoning keeps a
 * queued review in {@code pending_review} instead of marking its card.
 *
 * <p>Unlike {@code card}, these rows are droppable. One costs a single API call to recreate, so
 * holding a destructive migration hostage to a batch nobody has approved is the worse trade.
 */
@Entity(tableName = "candidate")
public class CandidateEntity {

    /**
     * Generated by the database, unlike {@code card.id}, which is minted by hand so local rows
     * cannot collide with server ids. A candidate is never addressed by the server and never
     * becomes a card by id, so it has nothing to keep out of the way of.
     */
    @PrimaryKey(autoGenerate = true)
    public long id;

    /** The topic the batch was generated for. Already a cached row when the batch was stored. */
    public long topicId;

    @NonNull
    public String front = "";

    @NonNull
    public String back = "";

    public Instant generatedAt;
}
