-- V1: topics, cards, and the append-only review log.
--
-- Scheduling state (ease factor, interval, repetitions, lapses, due date) lives on
-- `card` rather than in a side table: cards are user-authored, so a card and its
-- schedule are strictly 1:1. `review_log` is history for stats only and is never
-- read to compute the next schedule.
--
-- Every table carries `user_id` from day one. Auth is a single shared API key today,
-- but scoping the rows now means a real multi-user upgrade needs no data migration.

create table topic (
    id         bigint       generated by default as identity primary key,
    user_id    varchar(64)  not null,
    name       varchar(120) not null,
    slug       varchar(120) not null,
    created_at timestamptz  not null default now(),

    constraint uq_topic_user_slug unique (user_id, slug)
);

create table card (
    id               bigint           generated by default as identity primary key,
    user_id          varchar(64)      not null,
    topic_id         bigint           not null references topic (id) on delete restrict,
    front            text             not null,
    back             text             not null,

    -- Scheduling state. Defaults describe a brand new card: never reviewed, due today.
    ease_factor      double precision not null default 2.5,
    interval_days    integer          not null default 0,
    repetitions      integer          not null default 0,
    lapses           integer          not null default 0,
    due_date         date             not null default current_date,
    last_reviewed_at timestamptz,

    archived         boolean          not null default false,
    created_at       timestamptz      not null default now(),
    updated_at       timestamptz      not null default now(),

    -- These mirror the invariants SchedulingState enforces in Java. Duplicated on
    -- purpose: the database is the last line of defence against a bad write from
    -- anywhere, including psql.
    constraint ck_card_ease_factor check (ease_factor >= 1.3),
    constraint ck_card_interval    check (interval_days >= 0),
    constraint ck_card_repetitions check (repetitions >= 0),
    constraint ck_card_lapses      check (lapses >= 0)
);

-- The study queue is the hot path. Archived cards are never in it, so they are kept
-- out of the index entirely rather than filtered out at read time.
create index idx_card_due on card (user_id, due_date) where archived = false;

-- Supports "cards in this topic" and keeps the `on delete restrict` check cheap.
create index idx_card_topic on card (topic_id);

create table review_log (
    id                 bigint           generated by default as identity primary key,
    user_id            varchar(64)      not null,
    card_id            bigint           not null references card (id) on delete cascade,
    reviewed_at        timestamptz      not null default now(),
    confidence         integer          not null,

    -- Both sides of the transition are stored so a review can be understood without
    -- replaying every earlier row.
    interval_before    integer          not null,
    interval_after     integer          not null,
    ease_factor_before double precision not null,
    ease_factor_after  double precision not null,
    repetitions_after  integer          not null,

    constraint ck_review_confidence check (confidence between 1 and 5)
);

-- Stats and streaks scan by user over a date range, newest first.
create index idx_review_log_user_time on review_log (user_id, reviewed_at desc);

-- Serves "the history of this one card".
create index idx_review_log_card on review_log (card_id);
