-- V3: one row per accepted call to POST /cards/generate.
--
-- Generation is the only thing this application does that costs money on every request, and
-- it was the only one with nothing bounding how often it could be asked for. This table is
-- what the daily cap is counted from.
--
-- Append-only, like review_log, and for the same reason: a row records that something
-- happened. It is never updated and never deleted, so the count for a day cannot be walked
-- backwards by anything short of a manual delete.
--
-- Attempts are recorded, not successes. A call that reaches the upstream and fails has
-- already been paid for, so a cap that only counted successes would leave the expensive
-- case unlimited -- which is precisely backwards.

create table generation_request (
    id              bigint      generated by default as identity primary key,
    user_id         varchar(64) not null,

    -- What was asked for after clamping, so the row records the size of the call that was
    -- actually made rather than the number a caller typed. Enough to answer "how much did
    -- today cost" without keeping the prompt itself, which is the user's content and has no
    -- business being duplicated here.
    cards_requested integer     not null,

    created_at      timestamptz not null default now(),

    constraint ck_generation_cards_requested check (cards_requested > 0)
);

-- The cap's only query is "how many rows for this user since the start of today", so the
-- index leads with user_id and orders by time within it.
create index idx_generation_user_time on generation_request (user_id, created_at);
