-- V4: bearer tokens, so a credential stops having to be baked into a client build.
--
-- The shared API key is extractable from any APK that carries it, which makes one static
-- secret both the entire authentication and something that leaves the server permanently.
-- A token is issued to somebody who proved they know the passphrase, expires on its own,
-- and can be revoked without rebuilding an application.
--
-- X-API-Key still works while this lands. This migration adds a second way in; the removal
-- of the first is its own change.

create table auth_token (
    id         bigint      generated by default as identity primary key,
    user_id    varchar(64) not null,

    -- The SHA-256 of the token, hex, never the token itself. A token is 32 bytes of
    -- SecureRandom, so there is no guessing to slow down and a password hash here would only
    -- add its cost to every authenticated request. What this buys is that reading this table
    -- yields nothing usable: the value a client presents cannot be recovered from its digest.
    token_hash varchar(64) not null,

    expires_at timestamptz not null,
    created_at timestamptz not null default now(),

    -- Set when a token is withdrawn before it would have expired. Nullable because most
    -- tokens simply run out; a row is never deleted, so an issued token's fate stays legible.
    revoked_at timestamptz,

    -- Restates in the database what the service already guarantees, the same way the card
    -- constraints restate SchedulingState's invariants: a row that reached here by some route
    -- other than TokenService is still not allowed to hold a digest of the wrong shape.
    constraint ck_auth_token_hash_length check (char_length(token_hash) = 64),
    constraint ck_auth_token_expiry check (expires_at > created_at),
    constraint uq_auth_token_hash unique (token_hash)
);

-- Every authenticated request looks a token up by exactly this, and the unique constraint
-- above already provides the index that serves it. Nothing else queries this table on the
-- hot path, so there is deliberately no second index here to keep current.
