-- V6: one row per failed sign-in, which is what the rate limit is counted from.
--
-- POST /auth/login is the only route in this application an unauthenticated caller can put a
-- body into, and it deliberately runs bcrypt, which is expensive on purpose. That makes it two
-- surfaces at once: somewhere to guess a passphrase, and somewhere to spend a small instance's
-- CPU. Both are answered by refusing to do the work past a threshold.
--
-- Failures only. A client signing in successfully has proved it is the owner, and counting its
-- successes would eventually lock somebody out of their own account for using it.
--
-- Append-only, like generation_request and review_log. A row records that something happened;
-- the count for a window cannot be walked backwards.

create table login_attempt (
    -- Where the attempt appeared to come from. Nullable is deliberately not allowed: an
    -- unattributable attempt still has to be counted by the global limit, and a null would
    -- silently drop out of a `source = ?` comparison instead.
    source     varchar(64) not null,

    id         bigint      generated by default as identity primary key,
    created_at timestamptz not null default now()
);

-- Two queries read this table and this index serves both: how many failures from one source in
-- the window, leading with source; and how many from anyone, which scans the time range. The
-- second is why created_at is in the index at all rather than source alone.
create index idx_login_attempt_source_time on login_attempt (source, created_at);
create index idx_login_attempt_time on login_attempt (created_at);
